"""TCP/protobuf bridge that makes each simulated robot look like a real robot.

The wire format intentionally uses the same Protobuf_From_ROS and
Protobuf_From_BS messages as fukuro_communication. In local simulation, each
robot needs a different TCP port because all robots share one host/IP.
"""

import os

# The workspace currently ships protobuf code generated by the ROS Humble
# protoc. The pure-Python runtime keeps it compatible with newer protobuf
# Python packages without changing the real robot .proto contract.
os.environ.setdefault("PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION", "python")

import socket
import threading
import time
from typing import Callable

from geometry_msgs.msg import Pose2D

from fukuro_interface.msg import BaseStation, Obstacle, Robot, WorldState
from fukuro_interface.srv import StrategyChange
from fukuro_sim2d.protobuf import Protobuf_from_BS_pb2 as bs_pb2
from fukuro_sim2d.protobuf import Protobuf_from_ROS_pb2 as ros_pb2


def _copy_pose_to_proto(proto_pose, pose: Pose2D):
    proto_pose.x = float(pose.x)
    proto_pose.y = float(pose.y)
    proto_pose.theta = float(pose.theta)


def _pose_from_proto(proto_pose) -> Pose2D:
    return Pose2D(
        x=float(proto_pose.x),
        y=float(proto_pose.y),
        theta=float(proto_pose.theta),
    )


def _set_motor_wheel_set(wheel_set, values):
    # Match fukuro_communication's HardwareState mapping:
    # [0]=front, [1]=right_rear, [2]=left_rear.
    wheel_set.front = float(values[0]) if len(values) > 0 else 0.0
    wheel_set.right_rear = float(values[1]) if len(values) > 1 else 0.0
    wheel_set.left_rear = float(values[2]) if len(values) > 2 else 0.0


def _set_freewheel_set(wheel_set, values):
    # Match fukuro_communication's freewheel mapping:
    # [0]=front, [1]=left_rear, [2]=right_rear.
    wheel_set.front = float(values[0]) if len(values) > 0 else 0.0
    wheel_set.left_rear = float(values[1]) if len(values) > 1 else 0.0
    wheel_set.right_rear = float(values[2]) if len(values) > 2 else 0.0


def _team_color_to_string(value: int) -> str:
    if value == bs_pb2.TEAM_COLOR_CYAN:
        return "cyan"
    if value == bs_pb2.TEAM_COLOR_MAGENTA:
        return "magenta"
    return "unknown"


def _restart_type_to_string(value: int) -> str:
    names = {
        bs_pb2.RESTART_NONE: "RESTART_NONE",
        bs_pb2.RESTART_KICKOFF: "RESTART_KICKOFF",
        bs_pb2.RESTART_FREEKICK: "RESTART_FREEKICK",
        bs_pb2.RESTART_GOALKICK: "RESTART_GOALKICK",
        bs_pb2.RESTART_THROWIN: "RESTART_THROWIN",
        bs_pb2.RESTART_CORNER: "RESTART_CORNER",
        bs_pb2.RESTART_PENALTY: "RESTART_PENALTY",
        bs_pb2.RESTART_DROP_BALL: "RESTART_DROP_BALL",
    }
    return names.get(value, "RESTART_NONE")


class SimRobotCommsBridge:
    """Expose one simulated robot as a fukuro_communication-compatible server."""

    def __init__(
        self,
        *,
        node,
        agent,
        port: int,
        active: bool,
        world_state_getter: Callable[[object], WorldState],
        obstacle_getter: Callable[[], list[Obstacle]],
        enemy_getter: Callable[[], list],
        teammate_getter: Callable[[object], list],
        send_rate_hz: float = 30.0,
    ):
        self.node = node
        self.agent = agent
        self.port = int(port)
        self.active = bool(active)
        self.world_state_getter = world_state_getter
        self.obstacle_getter = obstacle_getter
        self.enemy_getter = enemy_getter
        self.teammate_getter = teammate_getter
        self.send_period = 1.0 / max(send_rate_hz, 1.0)

        self._stop_event = threading.Event()
        self._clients: list[socket.socket] = []
        self._clients_lock = threading.Lock()
        self._server_thread: threading.Thread | None = None
        self._last_send_time = 0.0
        self._last_velocity = (0.0, 0.0, 0.0)
        self._last_velocity_time = time.monotonic()
        self._wheel_ticks = [0.0, 0.0, 0.0]
        self._last_strategy_mode = ""

        self.base_station_pub = node.create_publisher(
            BaseStation, f"/{agent.name}/fukuro/comms/base_station", 10
        )
        self.strategy_change_client = node.create_client(
            StrategyChange, "/fukuro/strategy/change"
        )

    def start(self):
        if not self.active:
            self.node.get_logger().info(
                f"[{self.agent.name}] Sim protobuf bridge disabled"
            )
            return

        self._server_thread = threading.Thread(
            target=self._server_loop,
            name=f"{self.agent.name}_protobuf_bridge",
            daemon=True,
        )
        self._server_thread.start()

    def stop(self):
        self._stop_event.set()
        with self._clients_lock:
            clients = list(self._clients)
            self._clients.clear()
        for client in clients:
            try:
                client.shutdown(socket.SHUT_RDWR)
            except OSError:
                pass
            try:
                client.close()
            except OSError:
                pass
        if self._server_thread and self._server_thread.is_alive():
            self._server_thread.join(timeout=1.0)

    def publish_if_due(self):
        if not self.active:
            return
        now = time.monotonic()
        if (now - self._last_send_time) < self.send_period:
            return
        self._last_send_time = now
        payload = self._build_ros_proto().SerializeToString()
        self._send_to_clients(payload)

    def _server_loop(self):
        server = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        server.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
        try:
            server.bind(("0.0.0.0", self.port))
            server.listen(4)
            server.settimeout(0.5)
            self.node.get_logger().info(
                f"[{self.agent.name}] Sim protobuf bridge listening on port {self.port}"
            )
        except OSError as exc:
            self.node.get_logger().error(
                f"[{self.agent.name}] Failed to open sim protobuf port {self.port}: {exc}"
            )
            try:
                server.close()
            except OSError:
                pass
            return

        try:
            while not self._stop_event.is_set():
                try:
                    client, address = server.accept()
                except socket.timeout:
                    continue
                except OSError:
                    break

                client.settimeout(0.2)
                with self._clients_lock:
                    self._clients.append(client)
                self.node.get_logger().info(
                    f"[{self.agent.name}] Base station connected from {address[0]}:{address[1]}"
                )
                threading.Thread(
                    target=self._client_read_loop,
                    args=(client,),
                    name=f"{self.agent.name}_bs_reader",
                    daemon=True,
                ).start()
        finally:
            try:
                server.close()
            except OSError:
                pass

    def _client_read_loop(self, client: socket.socket):
        while not self._stop_event.is_set():
            try:
                data = client.recv(65536)
            except socket.timeout:
                continue
            except OSError:
                break
            if not data:
                break

            proto = bs_pb2.Protobuf_From_BS()
            try:
                proto.ParseFromString(data)
            except Exception as exc:
                self.node.get_logger().error(
                    f"[{self.agent.name}] Failed to parse Protobuf_From_BS: {exc}"
                )
                continue

            try:
                self._handle_base_station_proto(proto)
            except Exception as exc:
                self.node.get_logger().error(
                    f"[{self.agent.name}] Failed to handle Protobuf_From_BS: {exc}"
                )

        with self._clients_lock:
            if client in self._clients:
                self._clients.remove(client)
        try:
            client.close()
        except OSError:
            pass
        self.node.get_logger().info(f"[{self.agent.name}] Base station disconnected")

    def _send_to_clients(self, payload: bytes):
        with self._clients_lock:
            clients = list(self._clients)
        dead = []
        for client in clients:
            try:
                client.sendall(payload)
            except OSError:
                dead.append(client)

        if dead:
            with self._clients_lock:
                for client in dead:
                    if client in self._clients:
                        self._clients.remove(client)
            for client in dead:
                try:
                    client.close()
                except OSError:
                    pass

    def _build_ros_proto(self):
        ws = self.world_state_getter(self.agent)
        model = self.agent.model
        proto = ros_pb2.Protobuf_From_ROS()
        proto.timestamp.GetCurrentTime()

        _copy_pose_to_proto(proto.robot_position, ws.self_pose)
        _copy_pose_to_proto(proto.robot_velocity, ws.self_velocity)

        now = time.monotonic()
        dt = max(now - self._last_velocity_time, 1e-3)
        ax = (model.vx - self._last_velocity[0]) / dt
        ay = (model.vy - self._last_velocity[1]) / dt
        atheta = (model.omega - self._last_velocity[2]) / dt
        proto.robot_acceleration.x = ax
        proto.robot_acceleration.y = ay
        proto.robot_acceleration.theta = atheta
        self._last_velocity = (model.vx, model.vy, model.omega)
        self._last_velocity_time = now

        wheel_speeds = list(getattr(model, "omega_wheels", [0.0, 0.0, 0.0]))
        for i, speed in enumerate(wheel_speeds[:3]):
            self._wheel_ticks[i] += float(speed) * dt
        _set_motor_wheel_set(proto.motor_speed, wheel_speeds)
        _set_freewheel_set(proto.freewheel_speed, wheel_speeds)
        _set_motor_wheel_set(proto.motor_encoder_tick, self._wheel_ticks)
        _set_freewheel_set(proto.freewheel_encoder_tick, self._wheel_ticks)

        proto.ball_information.is_grip = bool(ws.is_ball_gripped)
        proto.ball_information.is_visible = bool(ws.is_ball_visible)
        proto.ball_information.is_visible_from = self.agent.name
        _copy_pose_to_proto(proto.ball_information.ball_pose, ws.ball_pose)
        _copy_pose_to_proto(proto.ball_information.ball_vel, ws.ball_velocity)

        proto.strategy_information.behaviour = self.agent.current_strategy
        proto.strategy_information.active_strategy = self.agent.current_strategy
        proto.strategy_information.state = self.agent.current_state
        proto.strategy_information.role = ws.dynamic_role or ws.robot_role
        proto.strategy_information.possible_state.extend(
            ["IDLE", "MOVING", "CATCHING", "HAS_BALL", "KICKING", "INTERCEPT"]
        )

        _copy_pose_to_proto(
            proto.steering_information.goal_pose, self.agent.latest_strategy_goal
        )
        _copy_pose_to_proto(proto.steering_information.target_lin_vel, ws.self_velocity)

        proto.ClearField("object_detected")
        for enemy in self.enemy_getter():
            obj = proto.object_detected.add()
            obj.object_name = "enemy_robot"
            obj.is_visible = True
            obj.is_visible_from = self.agent.name
            obj.object_pose.x = enemy.model.x
            obj.object_pose.y = enemy.model.y
            obj.object_pose.theta = enemy.model.theta
            obj.object_vel.x = enemy.model.vx
            obj.object_vel.y = enemy.model.vy
            obj.object_vel.theta = enemy.model.omega

        for teammate in self.teammate_getter(self.agent):
            obj = proto.object_detected.add()
            obj.object_name = "teammate_robot"
            obj.is_visible = True
            obj.is_visible_from = self.agent.name
            obj.object_pose.x = teammate.model.x
            obj.object_pose.y = teammate.model.y
            obj.object_pose.theta = teammate.model.theta
            obj.object_vel.x = teammate.model.vx
            obj.object_vel.y = teammate.model.vy
            obj.object_vel.theta = teammate.model.omega

        for obstacle in self.obstacle_getter():
            obj = proto.object_detected.add()
            obj.object_name = "obstacle"
            obj.is_visible = True
            obj.is_visible_from = self.agent.name
            _copy_pose_to_proto(obj.object_pose, obstacle.position)

        return proto

    def _handle_base_station_proto(self, proto):
        msg = self._base_station_msg_from_proto(proto)
        self.agent.last_base_station = msg
        self.base_station_pub.publish(msg)
        self._apply_base_station_control(msg)
        self._maybe_call_strategy_change(msg)

    def _base_station_msg_from_proto(self, proto) -> BaseStation:
        msg = BaseStation()
        msg.timestamp.sec = int(proto.timestamp.seconds)
        msg.timestamp.nanosec = int(proto.timestamp.nanos)
        msg.active_control = int(proto.active_control)
        msg.match_phase = int(proto.match_phase)
        msg.restart_type = int(proto.restart_command.type)
        msg.restart_for_us = bool(proto.restart_command.for_us)
        msg.defending_side = int(proto.defending_side)
        msg.sent_off = bool(proto.sent_off)
        msg.is_manual_control = bool(proto.is_manual_control)
        msg.manual_target_vel = _pose_from_proto(proto.manual_target_vel)
        msg.bs_ball_pose = _pose_from_proto(proto.bs_ball_pose)
        msg.has_initial_pose = proto.HasField("initial_pose")
        if msg.has_initial_pose:
            msg.initial_pose = _pose_from_proto(proto.initial_pose)

        msg.ball.pose = msg.bs_ball_pose
        msg.ball.is_detected = True

        for enemy_info in proto.enemy_robots:
            robot = Robot()
            robot.robot_pose = _pose_from_proto(enemy_info.robot_pose)
            robot.robot_vel = _pose_from_proto(enemy_info.robot_vel)
            robot.color_flag = _team_color_to_string(enemy_info.flag_color)
            msg.enemy_robots.append(robot)

        for friendly_info in proto.friendly_robots:
            robot = Robot()
            robot.robot_pose = _pose_from_proto(friendly_info.robot_pose)
            robot.robot_vel = _pose_from_proto(friendly_info.robot_vel)
            robot.path_goal = _pose_from_proto(friendly_info.path_goal)
            robot.robot_role = friendly_info.role
            robot.robot_state = friendly_info.state
            robot.is_ready = bool(friendly_info.is_ready)
            robot.color_flag = _team_color_to_string(friendly_info.flag_color)
            msg.friendly_robots.append(robot)

        for obstacle_info in proto.active_obstacles:
            obstacle = Obstacle()
            obstacle.position = _pose_from_proto(obstacle_info.position)
            obstacle.width = float(obstacle_info.width)
            obstacle.length = float(obstacle_info.length)
            msg.active_obstacles.append(obstacle)

        msg.active_strategy = _restart_type_to_string(proto.restart_command.type)
        return msg

    def _apply_base_station_control(self, msg: BaseStation):
        model = self.agent.model
        if msg.active_control == BaseStation.ACTIVE_CONTROL_STOP:
            self.agent.is_stopped = True
            model.reset_velocity()
        elif msg.active_control == BaseStation.ACTIVE_CONTROL_HOMING:
            self.agent.is_stopped = False
        elif msg.active_control == BaseStation.ACTIVE_CONTROL_START:
            self.agent.is_stopped = False

        if msg.is_manual_control and not self.agent.is_stopped:
            model.set_velocity(
                msg.manual_target_vel.x,
                msg.manual_target_vel.y,
                msg.manual_target_vel.theta,
            )

        if msg.has_initial_pose:
            model.x = msg.initial_pose.x
            model.y = msg.initial_pose.y
            model.theta = msg.initial_pose.theta
            model.reset_velocity()

    def _strategy_mode_from_base_station(self, msg: BaseStation) -> str:
        if msg.active_control == BaseStation.ACTIVE_CONTROL_STOP:
            return "stop"
        if msg.active_control == BaseStation.ACTIVE_CONTROL_HOMING:
            return "homing"
        if msg.active_control == BaseStation.ACTIVE_CONTROL_START:
            return "playing"
        return "idle"

    def _maybe_call_strategy_change(self, msg: BaseStation):
        strategy_mode = self._strategy_mode_from_base_station(msg)
        if strategy_mode == self._last_strategy_mode:
            return
        self._last_strategy_mode = strategy_mode

        if not self.strategy_change_client.service_is_ready():
            return

        request = StrategyChange.Request()
        request.new_strategy = strategy_mode
        self.strategy_change_client.call_async(request)
